const blankRow = () => ({ item: "", qty: "", unit: "" });

export default function TransactionTable({ title, documents, setDocuments, field, stockItems }) {
  const update = (documentIndex, rowIndex, key, value) => setDocuments(documents.map((document, index) => {
    if (index !== documentIndex) return document;
    if (rowIndex === null) return { ...document, [key]: value };
    const items = document.items.map((row, itemIndex) => itemIndex === rowIndex ? { ...row, [key]: value, ...(key === "item" ? { unit: stockItems.find((item) => item.id === Number(value))?.unit || "" } : {}) } : row);
    return { ...document, items };
  }));
  const changeRows = (documentIndex, callback) => setDocuments(documents.map((document, index) => index === documentIndex ? { ...document, items: callback(document.items) } : document));
  return <section className="report-section"><div className="section-title"><h2>{title}</h2><button className="btn btn-outline-secondary btn-sm" onClick={() => setDocuments([...documents, { [field]: "", items: [blankRow()] }])}>+ Add entry</button></div>{documents.map((document, documentIndex) => <div className="entry-card" key={documentIndex}><div className="entry-meta"><label>{field === "purchaseNo" ? "Purchase no." : "Gate pass no."}<input className="form-control" value={document[field]} onChange={(event) => update(documentIndex, null, field, event.target.value)} /></label><button className="btn btn-link text-danger" onClick={() => setDocuments(documents.filter((_, index) => index !== documentIndex))}>Remove</button></div><table className="table app-table"><thead><tr><th>Item</th><th>Quantity</th><th>Unit</th><th></th></tr></thead><tbody>{document.items.map((row, rowIndex) => <tr key={rowIndex}><td><select className="form-select" value={row.item} onChange={(event) => update(documentIndex, rowIndex, "item", event.target.value)}><option value="">Select item</option>{stockItems.map((item) => <option key={item.id} value={item.id}>{item.item_name}</option>)}</select></td><td><input type="number" min="0" className="form-control" value={row.qty} onChange={(event) => update(documentIndex, rowIndex, "qty", event.target.value)} /></td><td>{row.unit || "-"}</td><td><button className="icon-button" title="Add row" onClick={() => changeRows(documentIndex, (items) => [...items, blankRow()])}>+</button><button className="icon-button danger" title="Remove row" onClick={() => changeRows(documentIndex, (items) => items.length > 1 ? items.filter((_, index) => index !== rowIndex) : items)}>−</button></td></tr>)}</tbody></table></div>)}</section>;
}
